### PR TITLE
improv. fix island settings hook

### PR DESCRIPTION
**Pull request by nivcoo**
Hello, idk if you need the superioskyblock plugin before uploading the plugin but the plugin must be loaded before to be able to integrate the island settings.

### CODE REVIEW

**Comment by nivcoo** [comment]
I saw : pluginManager.isPluginEnabled("SuperiorSkyblock2") before register the settings, let me know if this line have to be changed by doesClassExist like shopGuiPlus

**Comment by OmerBenGera** [comment]
This fixes nothing or does anything special, as the checks are done on the first tick of the server, which means all the plugins are already loaded.

**Comment by nivcoo** [comment]
The plugin have to be load before SSB2 but you put SSB2 into softdepends and loadbefore so spigot load ws after ssb2

**Comment by OmerBenGera** [comment]
> 
> 
> The plugin have to be load before SSB2 but you put SSB2 into softdepends and loadbefore so spigot load ws after ssb2

I already fixed it by pushing a new update.
Your PR also changes a lot of other things which are not related to this issue and therefore it was rejected.
Also, for the next time, when you make PRs, give your commits better naming.

**Comment by nivcoo** [comment]
For the name it's just a fail. what is the "lot of other things" ?

**Comment by OmerBenGera** [comment]
> 
> 
> For the name it's just a fail. what is the "lot of other things" ?

the random condition that you changed, for example.

**Comment by nivcoo** [comment]
It's not random condtion, just the settings register condition which create the issue

**Comment by nivcoo** [comment]
I've 2 build, one with only the edit of plugin.yml and the otyher with the edited method, only the second build works

**Comment by OmerBenGera** [comment]
> 
> 
> I've 2 build, one with only the edit of plugin.yml and the otyher with the edited method, only the second build works

Why would checking if the plugin is enabled not work?

**Comment by OmerBenGera** [comment]
Not to mention that it works fine for me and probably everyone else.

**Comment by nivcoo** [comment]
Because of spigot ? It's works also for me if i've only SSB2 and ws but i've 98 plugins so maybe the load is busy and spigot do something which enabled ws after ssb2

**Comment by OmerBenGera** [comment]
> 
> 
> Because of spigot ? It works also for me if i've only SSB2 and ws but i've 98 plugins so maybe the load is busy and spigot do something which enabled ws after ssb2

If WildStacker has loadbefore for SSB, then it should be loaded before it unless something stupid is going on with your spigot jar.
Even if that's the case, changing that condition will not fix the issue in any way, as the plugin will still be loaded at the same time, causing the island flag to probably not get loaded.
If your spigot messes with that and causing that feature to not work, then don't use it.

**Comment by nivcoo** [comment]
> > Because of spigot ? It works also for me if i've only SSB2 and ws but i've 98 plugins so maybe the load is busy and spigot do something which enabled ws after ssb2
> 
> If WildStacker has loadbefore for SSB, then it should be loaded before it unless something stupid is going on with your spigot jar.
> Even if that's the case, changing that condition will not fix the issue in any way, as the plugin will still be loaded at the same time, causing the island flag to probably not get loaded.
> If your spigot messes with that and causing that feature to not work, then don't use it.

Why are you using this condition for Shopguiplus ?

**Comment by OmerBenGera** [comment]
> 
> 
> > > Because of spigot ? It works also for me if i've only SSB2 and ws but i've 98 plugins so maybe the load is busy and spigot do something which enabled ws after ssb2
> > 
> > 
> > If WildStacker has loadbefore for SSB, then it should be loaded before it unless something stupid is going on with your spigot jar.
> > Even if that's the case, changing that condition will not fix the issue in any way, as the plugin will still be loaded at the same time, causing the island flag to probably not get loaded.
> > If your spigot messes with that and causing that feature to not work, then don't use it.
> 
> Why are you using this condition for Shopguiplus ?

Because it looks for a specific version of SGP.

**Comment by nivcoo** [comment]
The issue is that the method isPluginEnabled return false but doesClassExist no

**Comment by OmerBenGera** [comment]
> 
> 
> The issue is that the method isPluginEnabled return false but doesClassExist no

Why would isPluginEnabled return false?

**Comment by OmerBenGera** [comment]
Also, from the issue that you reported, you received the following warning:
`Couldn't register a custom island-flag into SuperiorSkyblock - open an issue on github.`
This warning is called only if isPluginEnabled returns true for SSB.
The only issue is that WS is loaded after SSB on your server, which has nothing to do with the plugin but with your spigot.

**Comment by OmerBenGera** [comment]
My guess is that you use a custom spigot jar for 1.12.2, which messes with the order plugins load to your server.
This is not an issue with neither of the plugins, and therefore I am not gonna apply any changes to them.

**Comment by nivcoo** [comment]
I understand what you mean and your logic is correct but i don't understand why it doesn't work

**Comment by nivcoo** [comment]
Oh sorry i understand why my build works, i use the master... so i will try to build the dev and find the issue... but i have literally the issue with the dev and not the master branch, so it's not only my problem

**Pull request closed without merging**
